# Generated by Django 5.2.7 on 2025-12-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=True)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/cart/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('phone', 'product')},
        ),
    ]
