# Generated by Django 5.2.7 on 2025-12-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderdetails_alter_cart_image_alter_cart_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(default='0000000000', on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
